# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uilayout2.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(649, 707)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setMinimumSize(QtCore.QSize(130, 30))
        self.label_3.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_9.addWidget(self.label_3)
        self.identifier = QtWidgets.QLineEdit(self.frame_6)
        self.identifier.setMinimumSize(QtCore.QSize(400, 0))
        self.identifier.setMaximumSize(QtCore.QSize(400, 16777215))
        self.identifier.setObjectName("identifier")
        self.horizontalLayout_9.addWidget(self.identifier)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame_6)
        self.label.setEnabled(True)
        self.label.setMinimumSize(QtCore.QSize(130, 30))
        self.label.setMaximumSize(QtCore.QSize(130, 30))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.htmlDir = QtWidgets.QToolButton(self.frame_6)
        self.htmlDir.setMinimumSize(QtCore.QSize(25, 25))
        self.htmlDir.setMaximumSize(QtCore.QSize(25, 25))
        self.htmlDir.setObjectName("htmlDir")
        self.horizontalLayout.addWidget(self.htmlDir)
        self.label_htmlDir = QtWidgets.QLabel(self.frame_6)
        self.label_htmlDir.setMinimumSize(QtCore.QSize(375, 30))
        self.label_htmlDir.setMaximumSize(QtCore.QSize(375, 30))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_htmlDir.setFont(font)
        self.label_htmlDir.setMouseTracking(False)
        self.label_htmlDir.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_htmlDir.setObjectName("label_htmlDir")
        self.horizontalLayout.addWidget(self.label_htmlDir)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_6, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.asteriskCheck = QtWidgets.QCheckBox(self.frame_5)
        self.asteriskCheck.setMinimumSize(QtCore.QSize(200, 25))
        self.asteriskCheck.setMaximumSize(QtCore.QSize(200, 25))
        self.asteriskCheck.setChecked(True)
        self.asteriskCheck.setObjectName("asteriskCheck")
        self.verticalLayout.addWidget(self.asteriskCheck)
        self.frame_4 = QtWidgets.QFrame(self.frame_5)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkh1 = QtWidgets.QCheckBox(self.frame_4)
        self.checkh1.setMinimumSize(QtCore.QSize(40, 25))
        self.checkh1.setMaximumSize(QtCore.QSize(40, 25))
        self.checkh1.setChecked(False)
        self.checkh1.setObjectName("checkh1")
        self.horizontalLayout_2.addWidget(self.checkh1)
        self.checkh2 = QtWidgets.QCheckBox(self.frame_4)
        self.checkh2.setMinimumSize(QtCore.QSize(40, 25))
        self.checkh2.setMaximumSize(QtCore.QSize(40, 25))
        self.checkh2.setChecked(True)
        self.checkh2.setObjectName("checkh2")
        self.horizontalLayout_2.addWidget(self.checkh2)
        self.checkh3 = QtWidgets.QCheckBox(self.frame_4)
        self.checkh3.setMinimumSize(QtCore.QSize(40, 25))
        self.checkh3.setMaximumSize(QtCore.QSize(40, 25))
        self.checkh3.setObjectName("checkh3")
        self.horizontalLayout_2.addWidget(self.checkh3)
        self.checkh4 = QtWidgets.QCheckBox(self.frame_4)
        self.checkh4.setMinimumSize(QtCore.QSize(40, 25))
        self.checkh4.setMaximumSize(QtCore.QSize(40, 25))
        self.checkh4.setObjectName("checkh4")
        self.horizontalLayout_2.addWidget(self.checkh4)
        self.checkh5 = QtWidgets.QCheckBox(self.frame_4)
        self.checkh5.setMinimumSize(QtCore.QSize(40, 25))
        self.checkh5.setMaximumSize(QtCore.QSize(40, 25))
        self.checkh5.setObjectName("checkh5")
        self.horizontalLayout_2.addWidget(self.checkh5)
        self.verticalLayout.addWidget(self.frame_4)
        self.horizontalLayout_3.addWidget(self.frame_5)
        self.frame_7 = QtWidgets.QFrame(self.frame_2)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_7)
        self.label_2.setMinimumSize(QtCore.QSize(200, 25))
        self.label_2.setMaximumSize(QtCore.QSize(200, 25))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.indentS = QtWidgets.QRadioButton(self.frame_8)
        self.indentS.setMinimumSize(QtCore.QSize(60, 25))
        self.indentS.setMaximumSize(QtCore.QSize(60, 25))
        self.indentS.setChecked(True)
        self.indentS.setObjectName("indentS")
        self.horizontalLayout_5.addWidget(self.indentS)
        self.indentM = QtWidgets.QRadioButton(self.frame_8)
        self.indentM.setMinimumSize(QtCore.QSize(80, 25))
        self.indentM.setMaximumSize(QtCore.QSize(80, 25))
        self.indentM.setObjectName("indentM")
        self.horizontalLayout_5.addWidget(self.indentM)
        self.indentL = QtWidgets.QRadioButton(self.frame_8)
        self.indentL.setMinimumSize(QtCore.QSize(80, 25))
        self.indentL.setMaximumSize(QtCore.QSize(80, 25))
        self.indentL.setObjectName("indentL")
        self.horizontalLayout_5.addWidget(self.indentL)
        self.verticalLayout_2.addWidget(self.frame_8)
        self.horizontalLayout_3.addWidget(self.frame_7)
        self.gridLayout_2.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.copyAll = QtWidgets.QPushButton(self.frame_3)
        self.copyAll.setMinimumSize(QtCore.QSize(70, 30))
        self.copyAll.setMaximumSize(QtCore.QSize(70, 30))
        self.copyAll.setObjectName("copyAll")
        self.gridLayout_3.addWidget(self.copyAll, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(391, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_3)
        self.textBrowser.setMinimumSize(QtCore.QSize(0, 0))
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_3.addWidget(self.textBrowser, 1, 0, 1, 3)
        self.runButton = QtWidgets.QPushButton(self.frame_3)
        self.runButton.setMinimumSize(QtCore.QSize(70, 30))
        self.runButton.setMaximumSize(QtCore.QSize(70, 30))
        self.runButton.setObjectName("runButton")
        self.gridLayout_3.addWidget(self.runButton, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame_3, 2, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 649, 26))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BearNote-TOC-MonkeyApple v1.0"))
        self.label_3.setText(_translate("MainWindow", "Note\'s Identifier:"))
        self.label.setText(_translate("MainWindow", "Import:"))
        self.htmlDir.setText(_translate("MainWindow", "..."))
        self.label_htmlDir.setText(_translate("MainWindow", "choose the HTML File..."))
        self.asteriskCheck.setText(_translate("MainWindow", "Add (*) before headings:"))
        self.checkh1.setText(_translate("MainWindow", "h1"))
        self.checkh2.setText(_translate("MainWindow", "h2"))
        self.checkh3.setText(_translate("MainWindow", "h3"))
        self.checkh4.setText(_translate("MainWindow", "h4"))
        self.checkh5.setText(_translate("MainWindow", "h5"))
        self.label_2.setText(_translate("MainWindow", "Adjust Indent:"))
        self.indentS.setText(_translate("MainWindow", "small"))
        self.indentM.setText(_translate("MainWindow", "medium"))
        self.indentL.setText(_translate("MainWindow", "large"))
        self.copyAll.setText(_translate("MainWindow", "Copy All"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Open Sans\'; font-size:9.07563pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9.07563pt;\"><br /></p></body></html>"))
        self.runButton.setText(_translate("MainWindow", "Run"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
